#ifndef ENUMS_H_INCLUDED
#define ENUMS_H_INCLUDED

enum CGL_THEME     { CGL_THEME_DARK, CGL_THEME_CLEAR, CGL_THEME_BLACK, CGL_THEME_WHITE, CGL_THEME_FANCY };
enum CGL_INTERFACE { CGL_INTERFACE_RADIAL, CGL_INTERFACE_LINEAR };
enum CGL_BUTTONS   { CGL_BUTTONS_BASIC, CGL_BUTTONS_EXTENDED };
enum CGL_COLORS    { CGL_COLORS_FLASHY, CGL_COLORS_PASTEL, CGL_COLORS_WHITES, CGL_COLORS_COLD, CGL_COLORS_WARM };

#endif // ENUMS_H_INCLUDED
