#ifndef ENUMS_H_INCLUDED
#define ENUMS_H_INCLUDED

enum CGL_THEME       { CGL_THEME_DARK,         CGL_THEME_CLEAR,       CGL_THEME_BLACK,    CGL_THEME_WHITE, CGL_THEME_FANCY };
enum CGL_INTERFACE   { CGL_INTERFACE_RADIAL,   CGL_INTERFACE_LINEAR                                                       };
enum CGL_BUTTONS     { CGL_BUTTONS_BASIC,      CGL_BUTTONS_EXTENDED                                                       };
enum CGL_COLORS      { CGL_COLORS_FLASHY,      CGL_COLORS_PASTEL,     CGL_COLORS_WHITES,  CGL_COLORS_COLD, CGL_COLORS_WARM };
enum CGL_GROUND      {CGL_GROUND_SHADOWS,      CGL_GROUND_REFLECTION, CGL_GROUND_NONE};

enum CGL_CAM         { CGL_CAM_UPPER_SPHERE,   CGL_CAM_FULL_SPHERE,  CGL_CAM_ROTATING_OBJECTS                             };
enum CGL_ARRANGEMENT { CGL_ARRANGEMENT_CENTER, CGL_ARRANGEMENT_GRID, CGL_ARRANGEMENT_NATURAL                              };

#endif // ENUMS_H_INCLUDED
