// header file generated by txt2h, 2003-2006 by ScottManDeath
#ifndef  TXT_HEADER_simple_frag_code
#define  TXT_HEADER_simple_frag_code


const char simple_frag_code [] =
"#version 120\n"
"\n"
"varying vec3 fragmentColor;\n"
"\n"
"\n"
"void main(){\n"
"  gl_FragColor = vec4(fragmentColor,0.3);\n"
"}\n"
;


#endif  // #ifdef TXT_HEADER_simple_frag_code
